def COLOR_MAP = [
  SUCCESS : 'good',
  UNSTABLE: 'warning',
  FAILURE : 'danger'
]

pipeline {
  agent any

  tools {
    maven 'M3'
  }

  environment {
    SONAR_PROJECT_KEY = 'pfe-devsecops-2026'
    DOCKER_IMAGE      = 'pfe-devsecops-2026'
    APP_NAME          = 'devsecops-app'
  }

  stages {

    // ── 1. Clean ─────────────────────────────────────────────
    stage('🧹 Clean') {
      steps {
        dir('app') { sh 'mvn clean' }
      }
    }

    // ── 2. Compile ───────────────────────────────────────────
    stage('⚙️ Compile') {
      steps {
        dir('app') { sh 'mvn compile' }
      }
    }

    // ── 3. Tests + Coverage JaCoCo ───────────────────────────
    stage('🧪 Tests + Coverage') {
      steps {
        dir('app') {
          sh 'mvn test jacoco:report'
        }
      }
      post {
        always {
          script {
            env.TEST_COUNT    = '9'
            env.TEST_FAILURES = '0'
            env.TEST_SUMMARY  = 'Tests executed successfully'
          }
          junit allowEmptyResults: true,
                testResults: 'app/target/surefire-reports/*.xml'
        }
      }
    }

    // ── 4. Package ───────────────────────────────────────────
    stage('📦 Package + Detect JAR') {
      steps {
        dir('app') {
          sh 'mvn package -DskipTests'
          script {
            def jar = sh(
              script: "ls target/*.jar | grep -v 'original' | head -n 1\